#--------------------------------------------------------------
#          Makefile for unitcell module
#--------------------------------------------------------------

# List module object filenames
unitcell_objects =\
data.o \
exchange.o \
initialize.o \
initialize_shared.o \
interactions.o \
interface.o \
normalise.o \
read.o \
read_interactions.o \
set_exchange_type.o \
shells.o \
sc.o \
bcc.o \
bcc110.o \
cccro.o \
fcc.o \
fcc111.o \
fe3gete2.o \
fe5gete2.o \
file.o \
hcp.o \
heusler.o \
honeycomb.o \
honeycomb-a.o \
honeycomb-b.o \
kagome.o \
mn2au.o \
mn3sn.o \
nd2fe14b.o\
rocksalt.o \
rutile.o \
smfe12n.o\
spinel.o \
spinel-layered.o \
trigonal.o \
verify.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/unitcell/,$(unitcell_objects))
